version: '3.5'

services:
  postgres:
    container_name: postgres-shopper
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shopper
    volumes:
      - ./pgdata:/var/lib/postgres/data
    ports:
      - "5433:5432"